"""add leaderboard snapshots

Revision ID: cc0fb852f595
Revises: d54d6198763c
Create Date: 2026-09-09 22:36:32.445683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc0fb852f595'
down_revision: Union[str, Sequence[str], None] = 'd54d6198763c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_type', 'period_start', 'user_id', name='uq_leaderboard_period_user')
    )
    op.create_index(op.f('ix_leaderboard_snapshots_period_start'), 'leaderboard_snapshots', ['period_start'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_period_type'), 'leaderboard_snapshots', ['period_type'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_user_id'), 'leaderboard_snapshots', ['user_id'], unique=False)
    op.create_table('streaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_answer_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaks_user_id'), 'streaks', ['user_id'], unique=True)
    op.create_table('qotd_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('attempt_date', sa.Date(), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('base_points', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qotd_attempts_attempt_date'), 'qotd_attempts', ['attempt_date'], unique=False)
    op.create_index(op.f('ix_qotd_attempts_question_id'), 'qotd_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_qotd_attempts_user_id'), 'qotd_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qotd_attempts_user_id'), table_name='qotd_attempts')
    op.drop_index(op.f('ix_qotd_attempts_question_id'), table_name='qotd_attempts')
    op.drop_index(op.f('ix_qotd_attempts_attempt_date'), table_name='qotd_attempts')
    op.drop_table('qotd_attempts')
    op.drop_index(op.f('ix_streaks_user_id'), table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_leaderboard_snapshots_user_id'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_period_type'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_period_start'), table_name='leaderboard_snapshots')
    op.drop_table('leaderboard_snapshots')
    # ### end Alembic commands ###
